BEGIN;
SET random_page_cost to 2.0;
CREATE TEMP TABLE p_t (name text, id int) ON COMMIT DELETE ROWS;
CREATE TEMP TABLE s_t (name text, id int) ON COMMIT DELETE ROWS;
insert into s_t (name, id) select st.name, st.id from  states st order by name desc offset 0 limit 20;
insert into p_t (id, name) select id,name from products order by name asc offset 0 limit 10;
EXPLAIN ANALYZE VERBOSE select s.uid, sum(s.quantity*s.price) from  s_t st LEFT OUTER JOIN sales s ON s.uid=st.id group by s.uid;
EXPLAIN ANALYZE VERBOSE select s.pid, sum(s.quantity*s.price) from p_t p LEFT OUTER JOIN sales s ON s.pid=p.id  group by s.pid;
EXPLAIN ANALYZE VERBOSE select u.state, s.pid, sum(s.quantity*s.price) from s_t st, users u, p_t p, sales s where st.id = u.state and s.uid=u.id and s.pid=p.id group by u.state, s.pid;
COMMIT;
